
LIB =		datizo

SRCS +=		datizo.c
SRCS +=		datebsearch.c
SRCS +=		ParseDateTime.c
SRCS +=		DecodeNumberField.c
SRCS +=		ParseFractionalSecond.c
SRCS +=		DecodeNumber.c
SRCS +=		DecodeSpecial.c
SRCS +=		DecodeDate.c
SRCS +=		DecodeTime.c
SRCS +=		date2j.c
SRCS +=		j2date.c
SRCS +=		ValidateDate.c
#SRCS +=		DecodeDateTime.c
SRCS +=		pgstrcasecmp.c
SRCS +=		strtoi.c
#SRCS +=		timestamptz_in.c

SHLIB_MAJOR =	0
SHLIB_MINOR =	0

.include <bsd.lib.mk>
